### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by icydee** [Kantigen/ka-web#12]
Login page required in client using Web Socket interface.

Panel has two input text fields. 'username' and 'password'
Panel has two buttons, 'login' and 'register'.

'Login' button calls the web-socket client API 'loginWithPassword' and asynchronously receives the server response 'loginWithPassword', success or failure.

'Register' button brings up the 'Registration Page' see #13 

For client code see the following.
app/js/components/window/login.js

This is a start at this implementation but needs to implement the 'Register' button and needs to be integrated with the login process of the existing YUI code.

**Comment by nataliethistime** [comment]
This is basically done (over in my development branch). What remains is some server work and some polishing.

**Comment by nataliethistime** [comment]
Resolved by https://github.com/Kantigen/ka-web/commit/60902eb0189822a2b082fd1898f01bdb4d8f1bfd
