### ISSUE TITLE
Error in determining platform

### ISSUE THREAD

**Issue by icydee** [Kantigen/ka-web#18]
The platform of the client is determined in the 'load' function to decide which config file to load (currently mac or linux).

When running the client on a windows machine, it fails since it does not recognize 'win32' as a valid platform.

In the case where it does not recognize the platform it should still check for a 'user.json' config file and use just that.

**Comment by nataliethistime** [comment]
I didn't have a windows machine handy to test this while I was implementing it. Would I be correct in assuming that Windows, like Linux, uses `localhost` for Docker stuff? If that's the case, this is a quick fix..

**Comment by icydee** [comment]
I don't know about windows using localhost, my problem is I use a windows browser with the code running on linux so the auto detect is screwed

**Comment by nataliethistime** [comment]
Right, so it doesn't matter for you - you just need it to load `user.json`. 

Gotcha..

**Comment by nataliethistime** [comment]
Done :v:
