### ISSUE TITLE
New empire "do tutorial" button doesn't bring up email

### ISSUE THREAD

**Issue by dmcbride** [Kantigen/ka-web#4]
I suspect that we'll still do our tutorial via in-game email?

**Comment by nataliethistime** [comment]
This window will get moved over to using React some day. It'll get fixed, then. :wink:

**Comment by nataliethistime** [comment]
This was resolved by https://github.com/Kantigen/ka-web/commit/60902eb0189822a2b082fd1898f01bdb4d8f1bfd. The mail window wasn't being brought up by the button tutorial button handler.
