### ISSUE TITLE
Have a local Semantic

### ISSUE THREAD

**Issue by icydee** [Kantigen/ka-web#6]
Semantic UI is a good stop-gap but we need to be able to configure it.

We want to be able to customize it, e.g. smaller text, different fonts, whatever, which we can't do with the cloud version.

Also using a cloud version means it's harder to run totally off-line (for example developing on a plane or train).

If we could build it into the current UI then this would be cool.

**Comment by nataliethistime** [comment]
Once I get all the Docker stuff working I'll try taking a look at this. I think it would increase load times of the client in development, which would be a nice.

**Comment by nataliethistime** [comment]
Jah - this is done.
